### ISSUE TITLE
Request: usage statement

### ISSUE THREAD

**Issue by chrisgulvik** [marbl/MashMap#2]
The github page here is helpful but `mashmap -h` lacks a usage statement.

**Comment by cjain7** [comment]
`mashmap -h` should show a usage statement. Which version of code are you using? Also can you also re-check?

**Comment by cjain7** [comment]
I see now, it only shows list of available options, but not a usage example. I'll make sure to put one in the next release.

**Comment by chrisgulvik** [comment]
The v1.0 release is what I have been using.  `parsnp -h` is a nice example of handling a usage statement with complicated combinations of requirements.

**Comment by cjain7** [comment]
Thanks, fixed in the latest release.
