### ISSUE TITLE
Increased threshold for identity --pi generate more match dots

### ISSUE THREAD

**Issue by Raina-M** [marbl/MashMap#23]
Hi there,
I ran mashmap to compare the the contigs of one species to the genome of another species. But I found the dotplot showed more match dots when I set `--pi` as 90% than that when `--pi` was set as 85% (any other parameters are identical). What I understand is that higher `--pi` sets more strict constraints on matching, and the plot is expected to show less matching dots. Could you please give any interpretation about it?

--pi 85
![out](https://user-images.githubusercontent.com/33607735/69248617-da1f8280-0bac-11ea-8291-6ad61dd71aff.png)

--pi 90
![out](https://user-images.githubusercontent.com/33607735/69248684-fde2c880-0bac-11ea-8216-9a8c35d42a79.png)

**Comment by cjain7** [comment]
Hi, what filter mode `-f` are you using? You can try `one-to-one` mode to get best mappings among these. You're right that `--pi 90` should be more strict; but since Mashmap only provides guarantees on recall and not precision, there is always a risk of false-positives (i.e., matches below specified cutoff) in repetitive genomes. 
Also, in this case, with `--pi 90`, the implementation also switches to sparser sketch, which could also increase false positives.

**Comment by Raina-M** [comment]
@cjain7 , thank you. I did set `-f` as `one-to-one` mode. And I tried `--pi 95` later, and found it showing most clean dot plot (among 85, 90 and 95). So it seems that the number of matching fragments is not proportional to the threshold for identity. Like you mentioned, risk of false positive always exists, but this risk is supposed to be higher when `--pi` is lower, isn't it?
And why do you say `--pi 90` makes the implementation switch to sparser sketch? Isn't that `--kmer` affects the inspected sequence?

--pi 95%
![out](https://user-images.githubusercontent.com/33607735/69811609-bd0f3300-11ee-11ea-9799-99f7367cc954.png)

**Comment by cjain7** [comment]
>And why do you say --pi 90 makes the implementation switch to sparser sketch? 

The minimizer sampling density in the implementation is auto-tuned based on the specified length and identity cutoffs. The intuition is that with lower error-rate in the alignments, it suffices to sample fewer k-mers to locate them. This is done mainly to improve runtime and memory-usage.

> but this risk is supposed to be higher when --pi is lower, isn't it?
This is hard to say, would really depend on input data.

**Comment by Raina-M** [comment]
Thank you for the prompt reply. Your interpretation is very helpful.
