### ISSUE TITLE
Weird relationship between aligned segment length and read length

### ISSUE THREAD

**Issue by gbdias** [marbl/MashMap#27]
Hi,
- I used mashmap to align a set of PacBio reads to a reference genome and noticed a weird pattern in the relationship between read length and the aligned segment length.
- I then repeated the experiment using PacBio and ONT and comparing with minimap2 and I observe the same pattern for both sequencing data when using MashMap but not Minimap2.

  - Here is read length plotted against the aligned segment length.
<img width="1287" alt="Screen Shot 2020-02-18 at 11 06 12 AM" src="https://user-images.githubusercontent.com/7614153/74753836-b537bb80-523e-11ea-9caf-ce1e95475d7a.png">

  - And here is read length plotted against the aligned segment length as a fraction of read size.

<img width="1287" alt="Screen Shot 2020-02-18 at 11 04 37 AM" src="https://user-images.githubusercontent.com/7614153/74753869-c2ed4100-523e-11ea-88c3-cf2177e2a2ac.png">

- Maybe this is some known issue or maybe I'm doing something wrong but I thought I'd post this here in case you guys have any info.

#### Methods

- I originally noticed the pattern in our PacBio RS II and Sequel I unpublished data, and then I used the E.coli samples described in the Canu documentation for reproducing it and reporting it here. These include Pacbio and ONT reads.
https://canu.readthedocs.io/en/latest/quick-start.html#quickstart

- I used a conda install of mashmap 2.0 and ran it as follows:
`mashmap -t 10 -s 5000 -r ecoli_ref.fasta -q oxford.fasta`

- I also used a conda install of minimap2 2.17 and ran it with either PB or ONT presets.
`minimap2 -t 10 -cx map-pb ecoli_ref.fasta pacbio.fastq`

- I plotted alignments >= 5000 bp using ggplot's geom_point function.

- I did not retain a single alignment per read for my analysis. However, the vast majority of reads seem to produce a single alignment.

**Comment by cjain7** [comment]
Hi,

This behavior is due to the split-read mapping algorithm in Mashmap. It breaks each input read into non-overlapping segments (length 5000 by default, see option `segLength`), maps them individually and ties them together later if needed.

On the other hand, minimap2 uses a anchor chaining-based algorithm which makes it different.

**Comment by gbdias** [comment]
Got it, makes sense.
Thanks for clarifying!
