### ISSUE TITLE
generateDotPlot gives incomplete plot in postscript output

### ISSUE THREAD

**Issue by fernmoss** [marbl/MashMap#28]
Hi,
Thank you very much for creating MashMap.

Running `perl generateDotPlot 'postscript' 'medium' <mashmap ouptut file>` gave me a .ps file where the plot is cropped. 
The axis showing the reference is complete, but most of the axis showing the query is missing (only the largest few contigs are present in the plot). 
This was also the case when using the `'large'` option.

I imported the .ps file into GIMP 2.10.18. Changing the GIMP import rendering options (resolution, dimensions) did not make a difference. (*EDIT: GIMP cannot be the problem, I tried an online .ps to .jpg converter, the plot was incomplete)

The .png file created from the same MashMap output file is complete, no problem there.

What could be the issue? Is there anything I can do? 

Best regards

**Comment by cjain7** [comment]
I will take a look... but meanwhile, if you want to investigate at your end, you may want to check the gnuplot script `.gp` file, and see if it looks alright (i.e., follows correct gnuplot syntax).

**Comment by cjain7** [comment]
Also, it would be helpful if you can attach all the files (e.g., mashmap output, gnuplot script files) here. Also what version of gnuplot are you using?

**Comment by cjain7** [comment]
@fernmoss Let me know if you were able to resolve this issue. Thanks!

**Comment by elcortegano** [comment]
I was about to post a similar issue. In the reference genome I work with, there are more than 100 contigs (prefixed ctg), but only a few are present in the `.gp` file. Below I show the part corresponding to the reference axis:

```
set xtics rotate ( \
 "chromosome_6" 1.0, \
 "chromosome_12" 10785257.0, \
 "chromosome_10" 20299108.0, \
 "chromosome_3" 29351742.0, \
 "chromosome_2" 38144466.0, \
 "chromosome_16" 46829858.0, \
 "chromosome_9" 54775132.0, \
 "chromosome_17" 61451168.0, \
 "chromosome_7" 68020412.0, \
 "chromosome_13" 74200231.0, \
 "chromosome_8" 79347354.0, \
 "chromosome_11" 83885358.0, \
 "chromosome_15" 88144714.0, \
 "chromosome_14" 92401541.0, \
 "chromosome_4" 96473749.0, \
 "chromosome_5" 100247430.0, \
 "chromosome_1" 103700484.0, \
 "ctg52" 107043893.0, \
 "ctg55" 107133868.0, \
 "ctg58" 107191386.0, \
 "ctg62" 107245617.0, \
 "ctg65" 107291483.0, \
 "ctg66" 107334943.0, \
 "ctg54" 107368872.0, \
 "ctg134" 107446239.0, \
 "" 107455494.0 \
)
```

Interestingly, if I change the analysis, the contigs contained change, eg.:
```

set xtics rotate ( \
 "chromosome_6" 1.0, \
 "chromosome_12" 10785257.0, \
 "chromosome_10" 20299108.0, \
 "chromosome_3" 29351742.0, \
 "chromosome_2" 38144466.0, \
 "chromosome_16" 46829858.0, \
 "chromosome_9" 54775132.0, \
 "chromosome_17" 61451168.0, \
 "chromosome_7" 68020412.0, \
 "chromosome_13" 74200231.0, \
 "chromosome_8" 79347354.0, \
 "chromosome_11" 83885358.0, \
 "chromosome_15" 88144714.0, \
 "chromosome_14" 92401541.0, \
 "chromosome_4" 96473749.0, \
 "chromosome_5" 100247430.0, \
 "chromosome_1" 103700484.0, \
 "ctg53" 107043893.0, \
 "ctg55" 107146825.0, \
 "ctg122" 107204343.0, \
 "ctg59" 107225227.0, \
 "ctg106" 107273387.0, \
 "ctg60" 107287696.0, \
 "ctg71" 107334882.0, \
 "" 107368427.0 \
)
```

Why this behaviour? would it be possible to generate an output plot with all chromosomes and contigs as in the query and reference genomes entered?

**Comment by cjain7** [comment]
Hi, the visualisation script uses mashmap mapping output to get the chromosome/contig information. You'll notice that the script doesn't use the reference sequence as a command line parameter. The chromosome/contigs which are not part of any mapping won't get picked by the script.

**Comment by elcortegano** [comment]
Ok. In the output I was including output for two analyses with the same reference but different queries. If my understanding is correct, the contigs returned are different because the query genomes used do not cover exactly the same contigs in the reference, and cannot be mapped by mashmap (and consequently included as part of the dot plot). Am I right?

**Comment by cjain7** [comment]
Yes

**Comment by elcortegano** [comment]
Thank you again. I think the issue can be closed now.
