### ISSUE TITLE
/home/software/MashMap/mashmap: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gwaldbieser** [marbl/MashMap#3]
Please excuse my lack of informatics skills, but I'm having trouble with mashmap installation.
I'm using CentOS 7.3.1611 with gcc 4.8.5 20150623.
I installed gsl-2.4, then configured mashmap with:
$./bootstrap.sh
$./configure --with-gsl=/home/software/gsl-2.4/
$make
$/home/software/mashmap -s S15-132.contigs.fasta -q S15_132.1.subreads.fastq -o test1

Returns:
/home/software/MashMap/mashmap: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory

**Comment by gwaldbieser** [comment]
I also removed the Mashmap directory and did a clean installation using the prefix:
./configure --prefix=/usr/local/ --with-gsl=/home/software/gsl-2.4/
make

It does not install the binary in /usr/local/bin/ (it installs in the Mashmap directory) and still give the same error as above.

BTW, I am performing the install as 'root'.

**Comment by cjain7** [comment]
Can you try `--with-gsl=/home/software/gsl-2.4/build` and see if it works?

**Comment by gwaldbieser** [comment]
####Details below but that did not work.
####I removed the directory and did a fresh install:
[root@rambo software]# git clone https://github.com/marbl/MashMap.git
Cloning into 'MashMap'...
remote: Counting objects: 219, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 219 (delta 0), reused 3 (delta 0), pack-reused 211
Receiving objects: 100% (219/219), 120.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (115/115), done.
[root@rambo software]# cd MashMap/
[root@rambo MashMap]# ./bootstrap.sh
[root@rambo MashMap]# ./configure --with-gsl=/home/software/gsl-2.4/build
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking gsl/gsl_cdf.h usability... yes
checking gsl/gsl_cdf.h presence... yes
checking for gsl/gsl_cdf.h... yes
configure: creating ./config.status
config.status: creating Makefile
[root@rambo MashMap]# make
g++ -c -O3 -DNDEBUG -std=c++11 -Isrc -I /home/software/gsl-2.4/build/include -include src/common/memcpyLink.h -Wl,--wrap=memcpy  -o src/map/mash_map.o src/map/mash_map.cpp
g++ -O3 -DNDEBUG -std=c++11 -Isrc -I /home/software/gsl-2.4/build/include -include src/common/memcpyLink.h -Wl,--wrap=memcpy  src/map/mash_map.o   -o mashmap -L/home/software/gsl-2.4/build/lib -lgsl -lgslcblas -lstdc++ -lz -lm -lpthread
[root@rambo MashMap]# ./mashmap
./mashmap: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory

####Tried adding frontslash at end of 'build'
[root@rambo MashMap]# cd ..
[root@rambo software]# rm -rf MashMap/
[root@rambo software]# git clone https://github.com/marbl/MashMap.git
Cloning into 'MashMap'...
remote: Counting objects: 219, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 219 (delta 0), reused 3 (delta 0), pack-reused 211
Receiving objects: 100% (219/219), 120.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (115/115), done.
[root@rambo software]# cd MashMap/
[root@rambo MashMap]# ./bootstrap.sh
[root@rambo MashMap]# ./configure --with-gsl=/home/software/gsl-2.4/build/
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking gsl/gsl_cdf.h usability... yes
checking gsl/gsl_cdf.h presence... yes
checking for gsl/gsl_cdf.h... yes
configure: creating ./config.status
config.status: creating Makefile
[root@rambo MashMap]# make
g++ -c -O3 -DNDEBUG -std=c++11 -Isrc -I /home/software/gsl-2.4/build//include -include src/common/memcpyLink.h -Wl,--wrap=memcpy  -o src/map/mash_map.o src/map/mash_map.cpp
g++ -O3 -DNDEBUG -std=c++11 -Isrc -I /home/software/gsl-2.4/build//include -include src/common/memcpyLink.h -Wl,--wrap=memcpy  src/map/mash_map.o   -o mashmap -L/home/software/gsl-2.4/build//lib -lgsl -lgslcblas -lstdc++ -lz -lm -lpthread
[root@rambo MashMap]# ./mashmap -h
./mashmap: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
##

**Comment by cjain7** [comment]
This should be because linker is failing to find the gsl library in your library path.
In your environment file, you should update the `LD_LIBRARY_PATH` to include /home/software/gsl-2.4/build/lib

More details [here](https://www.gnu.org/software/gsl/manual/html_node/Shared-Libraries.html).

**Comment by gwaldbieser** [comment]
Hmm. My installation does not have a /build directory.
I re-downloaded v2.4 and reinstalled with “./configure && make && make install”

[root@rambo gsl-2.4]# ls
aclocal.m4    config.h       err              gsl_nan.h         INSTALL        mkinstalldirs       poly        sum
AUTHORS       config.h.in    fft              gsl.pc            install-sh     monte               qrng        sys
autogen.sh    config.log     fit              gsl.pc.in         integration    multifit            randist     templates_off.h
blas          config.status  gsl              gsl_pow_int.h     interpolation  multifit_nlinear    README      templates_on.h
block         config.sub     gsl-config       gsl_precision.h   libgsl.la      multilarge          rng         test
bspline       configure      gsl-config.in    gsl-randist       libtool        multilarge_nlinear  roots       test-driver
BUGS          configure.ac   gsl-histogram    gsl-randist.c     linalg         multimin            rstat       test_gsl_histogram.sh
build.h       const          gsl-histogram.c  gsl-randist.o     ltmain.sh      multiroots          siman       THANKS
cblas         COPYING        gsl-histogram.o  gsl.spec          Makefile       multiset            sort        TODO
cdf           depcomp        gsl_inline.h     gsl.spec.in       Makefile.am    NEWS                spblas      utils
ChangeLog     deriv          gsl.m4           gsl_types.h       Makefile.in    ntuple              specfunc    vector
cheb          dht            gsl_machine.h    gsl_version.h     matrix         ode-initval         splinalg    version.c
combination   diff           gsl_math.h       gsl_version.h.in  mdate-sh       ode-initval2        spmatrix    version.lo
complex       doc            gsl_minmax.h     histogram         min            permutation         stamp-h1    version.o
config.guess  eigen          gsl_mode.h       ieee-utils        missing        pkgconfig.test      statistics  wavelet

**Comment by gwaldbieser** [comment]
BTW, this is the Mashmap install but still have same result.

[root@rambo MashMap]# ll
total 24
-rwxr-xr-x. 1 root root    8 Aug 21 11:22 bootstrap.sh
-rw-r--r--. 1 root root 1405 Aug 21 11:22 configure.ac
-rw-r--r--. 1 root root 1665 Aug 21 11:22 INSTALL.txt
-rw-r--r--. 1 root root 1540 Aug 21 11:22 LICENSE.txt
-rw-r--r--. 1 root root  744 Aug 21 11:22 Makefile.in
-rw-r--r--. 1 root root 3498 Aug 21 11:22 README.md
drwxr-xr-x. 2 root root   36 Aug 21 11:22 scripts
drwxr-xr-x. 4 root root   41 Aug 21 11:22 src
[root@rambo MashMap]# ./bootstrap.sh
[root@rambo MashMap]# ./configure --with-gsl=/home/software/gsl-2.4/build
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking gsl/gsl_cdf.h usability... yes
checking gsl/gsl_cdf.h presence... yes
checking for gsl/gsl_cdf.h... yes
configure: creating ./config.status
config.status: creating Makefile
[root@rambo MashMap]# make
g++ -c -O3 -DNDEBUG -std=c++11 -Isrc -I /home/software/gsl-2.4/build/include -include src/common/memcpyLink.h -Wl,--wrap=memcpy  -o src/map/mash_map.o src/map/mash_map.cpp
g++ -O3 -DNDEBUG -std=c++11 -Isrc -I /home/software/gsl-2.4/build/include -include src/common/memcpyLink.h -Wl,--wrap=memcpy  src/map/mash_map.o   -o mashmap -L/home/software/gsl-2.4/build/lib -lgsl -lgslcblas -lstdc++ -lz -lm –lpthread

**Comment by cjain7** [comment]
Mashmap executable is not able to find the libgsl library. It is usually searched in the paths specified by the LD_LIBRARY_PATH environment variable.When you install gsl, it should generate the build libraries.

**Comment by gwaldbieser** [comment]
Yes, I understand. So apparently gsl is not installing properly since it does not produce a /build directory. I will try releases earlier than v2.4.

**Comment by cjain7** [comment]
Or it may be placing the libraries in some other directory. I am not sure what the default location is, perhaps `/usr/local/lib`?

**Comment by gwaldbieser** [comment]
Yes, they're in /usr/local/lib/ and I have tried to point to that during configuration and it seems happy to find the libraries there.
... 
[root@rambo Mashmap]$./bootstrap.sh
[root@rambo Mashmap]$./configure --with-gsl=/usr/local/lib

checking gsl/gsl_cdf.h usability... yes
checking gsl/gsl_cdf.h presence... yes
checking for gsl/gsl_cdf.h... yes
configure: creating ./config.status
config.status: creating Makefile

[root@rambo Mashmap]$make
[root@rambo Mashmap]$ ./mashmap
./mashmap: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory



###Here are the libraries in /usr/local/lib/
[root@rambo lib]$ ll libgsl*
-rw-r--r--. 1 root root 19081320 Aug 21 16:11 libgsl.a
-rw-r--r--. 1 root root  1757170 Aug 21 16:11 libgslcblas.a
-rwxr-xr-x. 1 root root      949 Aug 21 16:11 libgslcblas.la
lrwxrwxrwx. 1 root root       20 Aug 21 16:11 libgslcblas.so -> libgslcblas.so.0.0.0
lrwxrwxrwx. 1 root root       20 Aug 21 16:11 libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rwxr-xr-x. 1 root root  1047600 Aug 21 16:11 libgslcblas.so.0.0.0
-rwxr-xr-x. 1 root root      918 Aug 21 16:11 libgsl.la
lrwxrwxrwx. 1 root root       16 Aug 21 16:11 libgsl.so -> libgsl.so.19.3.0
lrwxrwxrwx. 1 root root       16 Aug 21 16:11 libgsl.so.19 -> libgsl.so.19.3.0
-rwxr-xr-x. 1 root root 11293856 Aug 21 16:11 libgsl.so.19.3.0

**Comment by skoren** [comment]
Is /usr/local/lib in LD_LIBRARY_PATH? What does echo $LD_LIBRARY_PATH report?

**Comment by gwaldbieser** [comment]
We upgraded the machine to contain larger HDDs so I reinstalled CentOS 7 and reinstalled the software. LD_LIBRARY_PATH was empty. After adding :/usr/lib to LD_LIBRARY_PATH then Mashmap works. Thank you.
