### ISSUE TITLE
output conversion to SAM/BAM file

### ISSUE THREAD

**Issue by SAMtoBAM** [marbl/MashMap#35]
Hi there, 
I have a polyploid genome that I want to map to a haploid reference and want to calculate the depth/number of contigs aligning at each region. Is there a way to convert your output tsv file into a SAM file in order so simplify this?

Thanks!

**Comment by Nheyer** [comment]
I am assuming your input to this was a fast file , can you not just align that using something like minimap2 ?

**Comment by SAMtoBAM** [comment]
Yes it is a fasta file for the query assembly
I have already done it with minimap2 using the asm5 option
I was wondering if MashMap would perform differently, particularly in repetitive regions

**Comment by Nheyer** [comment]
@treangen @skoren or @ondovb may be able to help you more, but generally mash map is used primarily for genome wide alignments where a SAM is not very useful so I would really trust minimap2 for your coverage data

**Comment by SAMtoBAM** [comment]
Genome wide alignments is exactly what I want, its just I can have 3-4 phased haplotypes assembled within a single polyploid genome. Plus with the default 'map' filter I should have the best position of all query contigs.
Yes, this may be the case, the SAM is not the best format for these genome wide alignments, it's purely that there are already simple pipelines in place for coverage analysis using SAM/BAM files so I was hoping to take advantage of this

Thanks for the help

**Comment by bkille** [comment]
Updating this issue for MashMap v3

The new version of mashmap outputs a [PAF](https://github.com/lh3/miniasm/blob/master/PAF.md) file. Unfortunately, [there are no plans](https://github.com/lh3/minimap2/issues/493#issuecomment-540531915) at the moment for `paftools.js` to support conversion from PAF to SAM/BAM.

**Comment by bkille** [comment]
Hi @SAMtoBAM,

You may be interested in the [rustybam](https://github.com/mrvollger/rustybam) toolkit, which supports PAF --> SAM conversion:

```
    paf-to-sam     Convert a PAF file into a SAM file. Warning, all alignments will be marked as
                   primary! [aliases: paftosam, p2s, paf2sam]
 ```

**Comment by ekg** [comment]
wfmash can produce BAM on top of mashmap's homology maps.
