### ISSUE TITLE
Current bioconda recipe doesn't seem to work

### ISSUE THREAD

**Issue by mjsteinbaugh** [marbl/MashMap#37]
I'm having trouble getting the current bioconda version of mashmap to work. Any advice?

See related bioconda-recipes issue https://github.com/bioconda/bioconda-recipes/issues/32329

Much appreciated!
Mike

**Comment by cjain7** [comment]
Mike, thanks for posting this issue. I'm closing it since you've already addressed it here https://github.com/bioconda/bioconda-recipes/issues/32329
