### ISSUE TITLE
Malformed line in output?

### ISSUE THREAD

**Issue by cmdcolin** [marbl/MashMap#38]
Hi there
I was computing an alignment between two chromosomes (human chr17 and gorilla chr5)

I ran this command

```
mashmap -r hg38_chr17.fa.gz -q gorgor6_chr5_2.fa.gz
```

The outputted file has a line where not all fields were filled in though

screenshot
![Screenshot from 2022-03-06 17-15-35](https://user-images.githubusercontent.com/6511937/156948688-34e66843-8241-44e4-82cd-73a7f0bd9017.png)

can attach full file if interested

**Comment by cmdcolin** [comment]
can verify this is mashmap 2.0 (would be great to have a --version flag to check :) i did it by shasum)

**Comment by cmdcolin** [comment]
I re-ran and did not get the same result so it could be random or infrequent

**Comment by cjain7** [comment]
Never observed such an issue before. Please let us know in case if you find any easy-to-reproduce recipe for this bug.

**Comment by cmdcolin** [comment]
can do, i will close just in case it was a fluke but will let you know if it happens again :)
