### ISSUE TITLE
 libgsl.so.25: cannot open shared object file

### ISSUE THREAD

**Issue by wook2014** [marbl/MashMap#39]
I have installed mashmap through conda, with version mashmap-2.0-pl5321h8e5b204_8, but it shows error " libgsl.so.25: cannot open shared object file". I checked on anaconda that the requirement of this version mashmap, it said 2.8>gsl>=2.7, and the file in /env/mashmap/bin is libgsl.so.27.

**Comment by cjain7** [comment]
Sorry I am not conda expert, maybe there are two versions of gsl on your system. The incorrect version is probably being loaded at runtime. Please check if adjusting `LD_LIBRARY_PATH` environment variable works. https://stackoverflow.com/a/24971971

**Comment by tdayris** [comment]
To fix this error, one should add : GSL package to the conda recipe. see : https://anaconda.org/conda-forge/gsl

**Comment by bkille** [comment]
@tdayris GSL has been added to the bioconda [recipe](https://bioconda.github.io/recipes/mashmap/README.html). Thanks for letting us know and please reopen if this doesn't fix the issue :slightly_smiling_face:
