### ISSUE TITLE
format of output file

### ISSUE THREAD

**Issue by shaomingfu** [marbl/MashMap#4]
Hi,

I am using mashmap with a small testing example as a start. My reference containing 100 sequences and query containing 5 sequences, and the query is exactly the first 5 sequences of the reference. I expect a perfect matching for each of the 5 query sequences. However, the first line of the output shows:
read1 2033 0 2032 + read1 2033 8 2040 98.9381 54 74 99.3103 0.943433

My questions are:
1, the length of read1 is 2033, so why the coordinates of target show 8 to 2040?
2, what does the last 5 numbers (98.9381 54 74 99.3103 0.943433) mean?

Thanks a lot!
Mingfu

**Comment by cjain7** [comment]
Hi, Can you try building mashmap from source on master branch and tell me if this issue is solved or not? The output format should exactly match with what README says.

Also, please review`./mashmap -h` in the latest version to make sure you are supplying the appropriate parameters for your needs.

**Comment by shaomingfu** [comment]
Thank you for your suggestions. I compiled mashmap from source code, and its output format matches the README description. 
However, when I run it on my data, it crashed after running 143 minutes (error message: terminate called after throwing an instance of 'std::bad_alloc'), while the released binary can finish running without any problem.

**Comment by cjain7** [comment]
Can you provide more details like how did you run mashmap (input arguments)?

**Comment by cjain7** [comment]
From 'std::bad_alloc', my first guess is it ran out of memory, but that should not happen at least for the dataset you described.

**Comment by shaomingfu** [comment]
mashmap -m 200 -q multi.fa -s PacBio.fa -o multi.out
where multi.fa contains 43457 sequences (actually they are transcripts) and PacBio.fa contains 3239918 sequences (they are BacBio long reads).

**Comment by cjain7** [comment]
`-m 200` is causing sketch density to be very high. Shorter this value, higher is the sketch size. Because the purpose of mashmap so far is finding approximate mapping boundaries/identity for mapping long DNA reads/contigs, we usually assume this length to be high (such as 2 Kbp or above, current default is 10 Kbp).

Also note that mashmap doesn't support spliced alignment/mapping. Also its not efficient for identifying short local alignments such as 200 bp.
