### ISSUE TITLE
k-mer size

### ISSUE THREAD

**Issue by TazinRahman1105050** [marbl/MashMap#40]
Dear concerned,

What is the largest value of k-mer works for MashMap? According to the help doc, we can use k-mer size up to 16. But I was running mashmap for some other experiments and found that k-mer size 20 also works.
Thanks in advance,
Tazin

**Comment by cjain7** [comment]
Mashmap uses 32 bit integer to save hashed k-mers. K-mers longer than 16 length will still get mapped to 32 bit space, leading to some degeneracy.

**Comment by TazinRahman1105050** [comment]
Thanks for the clarification

**Comment by bkille** [comment]
@TazinRahman1105050 

A year late here, but I wanted to let you know that k-mers are now mapped to the 64-bit space, so you can have larger k-mer sizes without needing to worry about degeneracy.
