### ISSUE TITLE
Impact of filtering options on genome alignment

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [marbl/MashMap#41]
Hi,

I'm interested in aligning microbial assemblies/closed genomes using MashMap. I am unsure of the difference between the various filtering options after trying to compare a few genomes.  Do you recommend using one-to-one mapping or none if I am interested in finding all blocks in both query/reference genomes that probably align?

**Comment by bkille** [comment]
Hi @jdwinkler-lanzatech,

Sorry for the late response. The goal of one-to-one is to obtain the orthologous mappings, whereas the regular mapping filter aims to identify all homologies. As a result, the one-to-one mapping will yield less mappings, but with a lower rate of "false-positive" mappings than the regular mapping mode.
