### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by foxyiris** [marbl/MashMap#5]
Hi,

I'm now trying to compile MashMap, and faced a compilation issue after following steps described in INSTALL.txt.
Could you please advise?

Used gcc v4.7.4/gsl v1.16, and static linking compilation was tried.
The error from compiler was shown below.
Thank you in advance.

**********************************
In file included from src/map/include/computeMap.hpp:23:0,
                 from src/map/mash_map.cpp:17:
src/map/include/slidingMap.hpp: In instantiation of ‘void skch::SlideMapper<Q_Info>::init() [with Q_Info = skch::QueryMetaData<std::vector<skch::MinimizerInfo> >]’:
src/map/include/slidingMap.hpp:106:11:   required from ‘skch::SlideMapper<Q_Info>::SlideMapper(Q_Info&) [with Q_Info = skch::QueryMetaData<std::vector<skch::MinimizerInfo> >]’
src/map/include/computeMap.hpp:642:41:   required from ‘double skch::Map::computeJaccardSinglePos(Q_Info&, skch::seqno_t, skch::offset_t) [with Q_Info = skch::QueryMetaData<std::vector<skch::MinimizerInfo> >; skch::seqno_t = int; skch::offset_t = int]’
src/map/include/computeMap.hpp:965:85:   required from here
src/map/include/slidingMap.hpp:123:13: error: ‘skch::SlideMapper<skch::QueryMetaData<std::vector<skch::MinimizerInfo> > >::MapType’ has no member named ‘emplace_hint’
make: *** [mashmap] Error 1

**Comment by foxyiris** [comment]
Hi cjain7,

Thank you for your advice!
Because of our environment, I changed the gcc version to 6.4.0 and gave up gsl due to the dependency. I tried boost this time.
I tried gcc 6.4.0/boost 1.57.0, but I got below error message this time.

In file included from src/map/mash_map.cpp:17:0:
src/map/include/computeMap.hpp: In member function ‘void skch::Map::mergeMappings(VecIn&)’:
src/map/include/computeMap.hpp:729:35: error: ‘accumulate’ is not a member of ‘std’
             it->nucIdentity = (   std::accumulate(it, it_end, 0.0,
                                   ^~~
make: *** [mashmap] Error 1

Please advise when you have some time. Thank you in advance!

**Comment by cjain7** [comment]
Thanks for pointing me this issue. I have added a missing header file. It should work now at your end.
