### ISSUE TITLE
mashmap-align very slow 

### ISSUE THREAD

**Issue by jianshu93** [marbl/MashMap#56]
Dear Mashmap3 team,

The mashmap command is very fast. However, mashmap.out to mashmap.sam file is extremely slow and use only one thread:

mashmap-align -s min17_fyle/DAS_bin_HQ_rename.fasta -q min17.noHost.sup1K.fastq --mappingFile mashmap.out --threads 24  --perc_identity 85

where mashmap.out is from the mashmap command. I am using the most recent version 3.0.5 compiled just now. Did I miss something? It is extremely slow to a level that it cannot be used in practice to have sam file for downstream analysis. 

Thanks,

Jianshu

**Comment by bkille** [comment]
Hi @jianshu93 

The `mashmap-align` command isn't being actively developed. I'd suggest using [wfmash](https://github.com/waveygang/wfmash):

```
mashmap -r ref.fa -q query.fa -o approx-map.paf --reportPercentage
```
Note that `wfmash` expects the `id` tag to be in the `[0, 100]` range, hence the `--reportPercentage` flag. You can then pass the ouput mappings from mashmap to wfmash via
```
wfmash ref.fa query.fa -i approx-map.paf > exact-align.paf
```

**Comment by jianshu93** [comment]
Hello @bkille 

I need the sam file output from wfmash, is that possible. My understanding of wfmash is that the wavefront algorithm only works for high than 95% matches, but I want down to 85% or 80% or so, which is only possible without wavefront. I feel like make sam files from mashmap out is easy right. 

Thanks,

Jianshu
