### ISSUE TITLE
Additional output

### ISSUE THREAD

**Issue by mvollger** [marbl/MashMap#7]
Hi, 

Not a bug report, or an issue, I was just wondering if there is any way to get out information about the actual alignment other than the percent identity? For my purposes I need to be able to examine the differences between the two regions. 

Is there a way to do this/do you have any plans for supporting it in the future?

Thanks!

**Comment by cjain7** [comment]
Hi, currently Mashmap2 does not generate alignments, but this is definitely in the plan.

**Comment by mvollger** [comment]
Okay, thanks for responding. 

I am curious, if that is the case how do you generate % Identity? Is it an estimate based on Jaccard similarity, or is it a "true" percent identity?

**Comment by cjain7** [comment]
It is based on Jaccard similarity. The estimation is done using a maximum likelihood estimator. You can refer to [Mash](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0997-x) paper to check out the equations.

**Comment by mvollger** [comment]
Thanks, I just wanted to make sure. 

Thanks for the help.
